### PR TITLE
Signup tenant backend

### PR DESCRIPTION
**Pull request by Amaya02**
Please Check

### CODE REVIEW

**Comment by oledanrozalyn** [comment]
Test Cases - Failed
1.) Test if user is able to Sign Up successfully when invalid email (without @) and password (less than 6 characters) are entered
2.) Test if the password will be visible if the check box for the show password is checked
3.) Test if the password will not be visible if the check box for the show password is not checked
4.) Verify if the user can Sign Up with an existing Company name
5.) Verify if the user can Sign Up with a password that is less than 6 characters

**Comment by Amaya02** [comment]
Will update. Thanks

**Comment by Amaya02** [comment]
Updated

**Comment by oledanrozalyn** [comment]
Approved

**Pull request merged**
