### PR TITLE
Signup tenant

### PR DESCRIPTION
**Pull request by Nevilstein**
please check

### CODE REVIEW

**Comment by sophiabarbon** [comment]
There's still a problem on the scroll bar in the signup modal

**Comment by Nevilstein** [comment]
Will update

**Comment by Nevilstein** [comment]
updated. please check

**Comment by sophiabarbon** [comment]
scroll bar still not fixed. please update

**Comment by Nevilstein** [comment]
updated. please check

**Comment by sophiabarbon** [comment]
approved.

**Pull request merged**
